_target_: m2_ovo_mae.models.mae.MaskedAutoencoderViT

img_size: 64
patch_size: 4
in_chans: 3

# Encoder (ViT-Lite)
embed_dim: 256
depth: 7
num_heads: 4
mlp_ratio: 2.0

# Decoder (Lightweight)
decoder_embed_dim: 128
decoder_depth: 2
decoder_num_heads: 4

# MAE Specifics
norm_pix_loss: false
